print(111)
print("""YOU ARE HACKED
      YOU ARE HACKED
      YOU ARE HACKED
      YOU ARE HACKED
      YOU ARE HACKED
      YOU ARE HACKED
      YOU ARE HACKED
      YOU ARE HACKED
      YOU ARE HACKED
      YOU ARE HACKED
      YOU ARE HACKED
      YOU ARE HACKED
      YOU ARE HACKED
      YOU ARE HACKED
      YOU ARE HACKED
      YOU ARE HACKED
      YOU ARE HACKED
YOU ARE HACKED
""")
